3012MVC/3012MVC/Areas/Admin/Controllers/KhuyenMaiController.cs
using _3012MVC.Areas.Admin.Models;
using _3012MVC.Models;
using PagedList;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace _3012MVC.Areas.Admin.Controllers
{
    public class KhuyenMaiController : Controller
    {
        // GET: Admin/KhuyenMai
        public ActionResult Index()
        {
            return View();
        }
        public bool UploadAnh(HttpPostedFileBase file, string tenfile)
        {
            // Verify that the user selected a file
            if (file != null && file.ContentLength > 0)
            {
                var name = Path.GetExtension(file.FileName);
                // extract only the filename
                if (!Path.GetExtension(file.FileName).Equals(".jpg"))
                {
                    return false;
                }
                // store the file inside ~/App_Data/uploads folder
                var path = Path.Combine(Server.MapPath("~/images/khuyenmai"), tenfile + ".jpg");
                file.SaveAs(path);
                return true;
            }
            // redirect back to the index action to show the form once again
            return false;
        }

        public bool DeleteAnh(string filename)
        {
            string fullPath = Request.MapPath("~/images/khuyenmai/" + filename);
            if (System.IO.File.Exists(fullPath))
            {
                System.IO.File.Delete(fullPath);
                return true;
            }
            return false;
        }
        public ActionResult ThemKhuyenMai()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ThemKhuyenMai([Bind(Include = "TENCT,NGAYBATDAU,NGAYKETTHUC,NOIDUNG")] KMAI loai, HttpPostedFileBase ad)
        {
            KhuyenMaiModel spm = new KhuyenMaiModel();
            if (ModelState.IsValid && spm.KiemTraTen(loai.TENCT))
            {
                string makm = spm.ThemKhuyenMai(loai);
                UploadAnh(ad, makm + "1");
            }
            return View("Index", loai);
        }
        public ActionResult EditKhuyenMai(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            KhuyenMaiModel lm = new KhuyenMaiModel();
            KMAI sp = lm.FindById(id);
            if (sp == null)
            {
                return HttpNotFound();
            }
            return View(sp);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditKhuyenMai([Bind(Include = "MAKM,TENCT,NGAYBATDAU,NGAYKETTHUC,NOIDUNG")] KMAI loai, HttpPostedFileBase ad)
        {
            KhuyenMaiModel spm = new KhuyenMaiModel();
            if (ModelState.IsValid)
            {
                spm.EditKhuyenMai(loai);
                UploadAnh(ad, loai.MAKM + "1");
                return RedirectToAction("Index");
            }
            return View(loai);
        }
        public ActionResult TimKhuyenMai(string key, DateTime? start, DateTime? end, int? page)
        {
            KhuyenMaiModel spm = new KhuyenMaiModel();
            ViewBag.key = key;
            ViewBag.start = start;
            ViewBag.end = end;
            return PhanTrangKhuyenMai(spm.TimKhuyenMai(key, start, end), page, null);
        }

        public ActionResult PhanTrangKhuyenMai(IQueryable<KMAI> lst, int? page, int? pagesize)
        {
            int pageSize = (pagesize ?? 10);
            int pageNumber = (page ?? 1);
            return PartialView("~/Areas/Admin/Views/KhuyenMai/_KhuyenMaiPartial.cshtml", lst.OrderBy(m => m.NGAYBATDAU).ToPagedList(pageNumber, pageSize));
        }
        public ActionResult SlideShowView()
        {
            KhuyenMaiModel km = new KhuyenMaiModel();
            return PartialView("~/Areas/Admin/Views/KhuyenMai/_SlideShowView.cshtml", km.TimKhuyenMai(null, null, null).Where(m => m.NGAYBATDAU <= DateTime.Today && m.NGAYKETTHUC >= DateTime.Today));
        }
        //[AllowAnonymous]
        //public ActionResult KhuyenMaiPost(string id)
        //{
        //    KhuyenMaiModel km = new KhuyenMaiModel();
        //    return View("KhuyenMaiPostView", km.FindById(id));
        //}
    }
}

3012MVC/3012MVC/Areas/Admin/Views/KhuyenMai/EditKhuyenMai.cshtml
@model _3012MVC.Models.KMAI

@{
    ViewBag.Title = "EditKhuyenMai";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}


@using (Html.BeginForm("EditKhuyenMai", "KhuyenMai", FormMethod.Post, new { id = "sualoaisp", autocomplete = "off", enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Sửa khuyến mãi</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.MAKM)

        <div class="form-group">
            @Html.LabelFor(model => model.NGAYBATDAU, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NGAYBATDAU, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NGAYBATDAU, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NGAYKETTHUC, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NGAYKETTHUC, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NGAYKETTHUC, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NOIDUNG, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NOIDUNG, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NOIDUNG, "", new { @class = "text-danger" })
            </div>
        </div>

		<div class="form-group">
			@Html.LabelFor(model => model.ANHCT, new { @class = "control-label col-md-2" })
			<div class="col-md-3">
				<input type="file" name="ad" accept=".jpg" class="form-control" />
			</div>
		</div>

        <div class="form-group">
            @Html.LabelFor(model => model.TENCT, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TENCT, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TENCT, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

3012MVC/3012MVC/Areas/Admin/Views/KhuyenMai/Index.cshtml
@model _3012MVC.Models.KMAI
@{
	ViewBag.Title = "Index";
	Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="row">
	<div class="box col-md-12">
		<div class="box-inner">
			<div class="box-content">

				<div class="alert alert-info" id="alert-info" style="display:none"></div>
				<div class="form-inline" padding: 10px">
					<a href="~/Admin/KhuyenMai/ThemKhuyenMai" class="btn btn-info">Thêm Khuyễn mãi</a>
					</div>
					@*<div class="form-inline" style="text-align: right; padding: 10px">
						<div class="input-group">
							<span class="input-group-addon"><i class="red">Start</i></span>
							<input id="startday" type="date" class="form-control" onchange="timkiemKhuyenMai()">
						</div>

						<div class="input-group">
							<span class="input-group-addon"><i class="red">End</i></span>
							<input id="endday" type="date" class="form-control" onchange="timkiemKhuyenMai()">
						</div>

						<div class="input-group">
							<span class="input-group-addon"><i class="glyphicon glyphicon-search red"></i></span>
							<input id="inputIcon" type="text" class="form-control" placeholder="Nhập tên chương trình" oninput="timkiemKhuyenMai()">
						</div>


					</div>*@
					<div class="Ajax-Table">
						@Html.Action("TimKhuyenMai", "KhuyenMai")
					</div>

				</div>
		</div>
	</div>
	<!--/span-->
</div><!--/row-->

3012MVC/3012MVC/Areas/Admin/Views/KhuyenMai/ThemKhuyenMai.cshtml
@model _3012MVC.Models.KMAI

@{
	ViewBag.Title = "ThemKhuyenMai";
	Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="row">
	<div class="box col-md-12">
		<div class="box-inner">
		
			<div class="box-content">

				@using (Html.BeginForm("ThemKhuyenMai", "KhuyenMai", FormMethod.Post, new { autocomplete = "off", enctype = "multipart/form-data" }))
				{

					<div class="form-horizontal">
						<div class="alert alert-info" style="display:none">
							@Html.AntiForgeryToken()
							@Html.ValidationSummary()
							<span id="kiemtratrung"></span>
						</div>
						<div class="form-group">
							@Html.LabelFor(model => model.TENCT, new { @class = "control-label col-md-2" })
							<div class="col-md-4">
								@Html.TextBoxFor(model => model.TENCT, new { @class = "form-control", oninput = "kiemgiatritrung(this.value,\"" + @Url.Action("kiemtra", "KhuyenMai") + "\",\"#loaiisok\")" })
								@Html.ValidationMessageFor(model => model.TENCT)
								<span id="loaiisok"></span>
							</div>
						</div>

						<div class="form-group">
							@Html.LabelFor(model => model.NGAYBATDAU, new { @class = "control-label col-md-2" })
							<div class="col-md-3">
								@Html.EditorFor(model => model.NGAYBATDAU, new { htmlAttributes = new { @class = "form-control" } })
								@Html.ValidationMessageFor(model => model.NGAYBATDAU)
							</div>
						</div>

						<div class="form-group">
							@Html.LabelFor(model => model.NGAYKETTHUC, new { @class = "control-label col-md-2" })
							<div class="col-md-3">
								@Html.EditorFor(model => model.NGAYKETTHUC, new { htmlAttributes = new { @class = "form-control" } })
								@Html.ValidationMessageFor(model => model.NGAYKETTHUC)
							</div>
						</div>

						<div class="form-group">
							@Html.LabelFor(model => model.ANHCT, new { @class = "control-label col-md-2" })
							<div class="col-md-3">
								<input type="file" name="ad" accept=".jpg" class="form-control" onchange="readURL(this, '#anhdaidien');" />
							</div>
						</div>

						<div class="form-group">
							@Html.LabelFor(model => model.NOIDUNG, new { @class = "control-label col-md-2" })
							<div class="col-md-10">
								@Html.TextAreaFor(model => model.NOIDUNG, new { @class = "form-control" })
								@Html.ValidationMessageFor(model => model.NOIDUNG)
								<script>
									CKEDITOR.replace('NoiDung');
								</script>
							</div>
						</div>

						<div class="form-group">
							<div class="col-md-offset-2 col-md-10">
								<input type="submit" value="Thêm mới" class="btn btn-default" />
							</div>
						</div>
					</div>
				}

			</div>

		</div>
	</div>
	<!--/span-->
</div><!--/row-->

3012MVC/3012MVC/Areas/Admin/Views/KhuyenMai/_KhuyenMaiPartial.cshtml
@using _3012MVC.Models;
@using PagedList;
@using PagedList.Mvc;
@model PagedList.IPagedList<KMAI>


<table class="table table-striped table-bordered bootstrap-datatable datatable responsive">
	<thead>
		<tr>
			<th>@Html.DisplayNameFor(model => model.First().TENCT)</th>
			<th>@Html.DisplayNameFor(model => model.First().NGAYBATDAU)</th>
			<th>@Html.DisplayNameFor(model => model.First().NGAYKETTHUC)</th>
			<th>@Html.DisplayNameFor(model => model.First().ANHCT)</th>
			<th>#</th>
		</tr>
	</thead>
	<tbody>
		@foreach (var item in Model)
		{
			<tr>
				
				<td class="center">@item.TENCT</td>
				<td class="center">
					@if (item.NGAYBATDAU != null)
					{@item.NGAYBATDAU.Value.ToShortDateString()}
				</td>
				<td class="center">
					@if (item.NGAYKETTHUC != null)
					{@item.NGAYKETTHUC.Value.ToShortDateString()}
				</td>
				<td class="center"><img src="@Url.Content("~/images/khuyenmai/")@item.ANHCT" width="150" height="80" /></td>
				<td class="center">
					<a class="btn btn-info" href="@Url.Action("EditKhuyenMai", "KhuyenMai", new { id = item.MAKM })">
						<i class="glyphicon glyphicon-edit icon-white"></i>
					</a>
				</td>
			</tr>
		}
	</tbody>
</table>

<div class="pagination-holder">
	<div class="row">
		<div class="col-xs-12 col-sm-6 text-left">
			<div id="nav_grid">
				@Html.PagedListPager(Model, page => Url.Action("TimKhuyenMai", "KhuyenMai", new { key = @ViewBag.key, start = @ViewBag.start, end = @ViewBag.end, page = page }))
			</div>
		</div>
		
	</div><!-- /.row -->
</div><!-- /.pagination-holder -->

<div id="show-dialog-detail" style="display:none">
</div>

3012MVC/3012MVC/Areas/Admin/Views/KhuyenMai/_SlideShowView.cshtml
@model IQueryable<_3012MVC.Models.KMAI>

<div id="hero">
	<div id="owl-main" class="owl-carousel height-lg owl-inner-nav owl-ui-lg">
		@foreach (var item in Model)
		{
			<div class="item" style="background-image: url('@Url.Content("~/images/khuyenmai/")@item.ANHCT'); cursor:pointer" @*onclick="window.location = '@Url.Action("KhuyenMaiPost","KhuyenMai")?id=' + @item.MAKM;"*@>
				<div class="container-fluid">
				</div><!-- /.container-fluid -->
			</div><!-- /.item -->
		}
	</div><!-- /.owl-carousel -->
</div>