3012MVC/3012MVC/Models/QuenMatKhau.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace _3012MVC.Models
{
	public class QuenMatKhau
	{
		public int MaQuenMatKhau { get; set; }
		public string EmailNhan { get; set; }
		public string ChuDe { get; set; }
		public string NoiDung { get; set; }
		public string Bcc { get; set; }
		public string Cc { get; set; }
	}
}

3012MVC/3012MVC/Controllers/QuenMatKhauController.cs
using _3012MVC.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;

namespace _3012MVC.Controllers
{
    public class QuenMatKhauController : Controller
    {
		// GET: QuenMatKhau
		Shopbanhang db = new Shopbanhang();
		public ActionResult GuiMail()
		{
			return View();
		}
		[HttpPost]
		public ActionResult GuiMail(QuenMatKhau qmk)
		{
			try
			{
				// Định cấu hình lớp webMail để gửi email  
				// máy chủ gmail smtp  
				WebMail.SmtpServer = "smtp.gmail.com";
				// cổng gmail để gửi email  
				WebMail.SmtpPort = 587;
				WebMail.SmtpUseDefaultCredentials = true;
				// gửi email với giao thức bảo mật  
				WebMail.EnableSsl = true;
				// EmailId được sử dụng để gửi email từ ứng dụng  
				WebMail.UserName = "vuongminhm10@gmail.com";
				WebMail.Password = "38c109096";

				// Địa chỉ email người gửi.  
				WebMail.From = "vuongminhm10@gmail.com";
				USSER nd = db.USSERs.FirstOrDefault(t => t.EMAIL == qmk.EmailNhan);
				qmk.ChuDe = "Xác nhận đổi mật khẩu ";
				qmk.NoiDung = "Xác nhận:'https://localhost:44348/QuenMatKhau/Thaydoimatkhau/" + nd.ID + "?Token=" + nd.Token;

				//Gửi email  
				WebMail.Send(to: qmk.EmailNhan, subject: qmk.ChuDe, body: qmk.NoiDung, cc: qmk.Cc, bcc: qmk.Bcc, isBodyHtml: true);
				ViewBag.Status = "Email được gửi thành công.";
			}
			catch (Exception)
			{
				ViewBag.Status = "Sự cố trong khi gửi email, vui lòng kiểm tra chi tiết.";
			}
			return View();
		}
		[HttpGet]
		public ActionResult Thaydoimatkhau()
		{
			return View();
		}
		[HttpPost]
		public ActionResult Thaydoimatkhau(string matkhaumoi, string nhaplaimatkhau, int? id, string Token)
		{
			if (matkhaumoi != nhaplaimatkhau)
			{
				ViewBag.TB = "Mật khẩu không đúng! ";
				return View();
			}
			else
			{
				db.USSERs.Find(id).PASS = matkhaumoi;
				db.SaveChanges();
				return Redirect("/");
			}
		}
	}
}

3012MVC/3012MVC/Views/QuenMatKhau/GuiMail.cshtml
@{
	ViewBag.Title = "GuiMail";
	Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="col-md-8 wow fadeInRight" data-wow-delay="0.4s">
	<div class="alert alert-success">
		<h2 style="color: brown">Khôi phục mật khẩu?</h2>
		<center><h4 style="color: black">Hãy nhập email bạn đã đăng kí, FreeCode sẽ gửi đường link tạo mật khẩu mới vào email của bạn.</h4></center>
		<form action="@Url.Action("GuiMail", "QuenMatKhau")" method="post">
			<b>Email đăng nhập</b>
			<input type="email" name="EmailNhan" class="form-control" placeholder="Vui lòng nhập gmail..." required />
			<p style="color: red">@ViewBag.Status</p>
			<br />
			<center> <input type="submit" value="Lấy lại mật khẩu" class="btn btn-danger" /></center>

		</form>
	</div>
</div>

3012MVC/3012MVC/Views/QuenMatKhau/Thaydoimatkhau.cshtml
@{
    ViewBag.Title = "Thaydoimatkhau";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

	<div class="modal fade" id="exampleModalqq" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
		<div class="modal-dialog" role="document">
			<div class="modal-content">
				<form action="@Url.Action("Login", "User")" method="post">
					<center><b><i class="fas fa-keyboard" style="color: green; font-size: 40px;"></i><span style="color: red; font-size: 40px">F</span><span style="color: #4267b2; font-size: 25px;">ree</span><span style="color: green; font-size: 40px;">C</span><span style="color: #4267b2; font-size: 25px;">ode</span></b></center>
					<center><b style="font-size: 25px;"><i class="fas fa-sign-in-alt">&nbsp;</i>Đăng nhập</b></center>
					<br />
					<center style="font-size:15px;"><b>Bạn chưa có tài khoản! <a href="#" style="text-decoration: none; color: green;">Đăng ký ngay</a></b></center>
					<center style="margin-top: 5%">
						<input type="email" class="form-control" style="width: 60%" required placeholder="Nhập vào Email của bạn..." name="txtTaiKhoan" />
						<br />
						<input type="password" class="form-control" style="width: 60%" required placeholder="Nhập vào mật khẩu của bạn" name="txtMatKhau" />
						<br />
						<button class="btn btn-danger" style="width: 60%">Đăng nhập</button>
						<br />
					</center>
					<a href="@Url.Action("GuiMail", "QuenMatKhau")" style="margin-left: 20%; color:orange"><i>Quên mật khẩu?</i></a>
				</form>
				</div>
			</div></div>