3012MVC/3012MVC/Areas/Admin/Controllers/SanphamController.cs
using _3012MVC.Models;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;
using _3012MVC.Areas.Admin.Models;
using _3012MVC.Common;

namespace _3012MVC.Areas.Admin.Controllers
{

	[HasCredential(RoleID = "VIEW_USER")]
	public class SanphamController : Controller
    {
		
		Shopbanhang db = new Shopbanhang();
		public ActionResult Loadsanpham()
		{
			return View();
		}
		[HttpGet]
		public JsonResult sanpham()
		{
			SanphamModel sanpham = new SanphamModel();
			var model = sanpham.Getsp();

			return this.Json(
			  new
			  {
				 data = (from obj in db.SPHAMs select new { MASP = obj.MASP, TENSP = obj.TENSP,
					 LOAISP=obj.LOAISP,
					 HANGSX=obj.HANGSX,
					 GIA= obj.GIA,
					 SOLUONG=obj.SOLUONG,
					 MOTA=obj.MOTA,
					 ANHDAIDIEN=obj.ANHDAIDIEN
				 })
			  }
			  , JsonRequestBehavior.AllowGet
			  );

		}
		[HttpPost]
		public JsonResult deletesanpham(string MASP)
		{
			new SanphamModel().deletesp(MASP);
			return Json(new
			{
				status = true
			}, JsonRequestBehavior.AllowGet);
		}
		public ActionResult themsp()
		{
			 SanphamModel sp = new SanphamModel();
			ViewBag.HANGSX = new SelectList(sp.Gethangsanxuat(), "HANGSX", "TENHANG ");
			ViewBag.LOAISP = new SelectList(sp.Getloaisp(), "MALOAI", "TENLOAI");
			return View();
		}
		public bool UploadAnh(HttpPostedFileBase file, string tenfile)
		{
			// Verify that the user selected a file
			if (file != null && file.ContentLength > 0)
			{
				var name = Path.GetExtension(file.FileName);
				// extract only the filename
				if (!Path.GetExtension(file.FileName).Equals(".jpg"))
				{
					return false;
				}
				// store the file inside ~/App_Data/uploads folder
				var path = Path.Combine(Server.MapPath("~/images/products"), tenfile + ".jpg");
				file.SaveAs(path);
				return true;
			}
			// redirect back to the index action to show the form once again
			return false;
		}
		[HttpPost]
		public ActionResult Addsanpham([Bind(Include = "TENSP,LOAISP,HANGSX,GIA,MOTA,SOLUONG,ISNEW")] SPHAM sanpham, HttpPostedFileBase an)
		{
			SanphamModel spm = new SanphamModel();
			if(ModelState.IsValid){
				string masp = spm.themsp(sanpham);
				UploadAnh(an, masp + "1");//waring masp+1 not get picture up to list 
			}
			ViewBag.HANGSX = new SelectList(spm.Gethangsanxuat(), "HANGSX", "TENHANG ");
			ViewBag.LOAISP = new SelectList(spm.Getloaisp(), "MALOAI", "TENLOAI");
			return View("themsp",sanpham);
		}
	}
}

3012MVC/3012MVC/Areas/Admin/Views/Sanpham/Loadsanpham.cshtml
@{
	ViewBag.Title = "Loadsanpham";
}

<a href="~/Admin/Sanpham/themsp" class="btn btn-info btn-lg">add</a>
<table class="table table-striped table-bordered bootstrap-datatable datatable responsive">
	<thead>
		<tr>
			<th>
				Tên
			</th>

			<th>
				Loại sản phẩm
			</th>
			<th>
				hãng sản xuất
			</th>
			<th>
				giá
			</th>
			<th>
				số lượng
			</th>

			<th>
				mô tả
			</th>
			<th>
				ảnh
			</th>
			<th>
				#
			</th>

		</tr>
	</thead>
	<tbody id="sp">
	</tbody>
</table>

<script id="teamplatesanpham" type="x-tpml-mustache">
	<tr>
		{{MASP}}
		<td>
			{{TENSP}}
		</td>

		<td>
			{{LOAISP}}
		</td>
		<td>
			{{HANGSX}}
		</td>
		<td>
			{{GIA}}
		</td>
		<td>
			{{SOLUONG}}
		</td>
		<td>
			{{MOTA}}
		</td>
		<td>
			{{ANHDAIDIEN}}
		</td>
		<td>
			<button class="btn btn-primary btn-edit" data-id="{{MASP}}"><i class="fa fa-edit"></i></button>

			<button class="btn btn-danger" data-id="{{MASP}}"><i class="fa fa-trash"></i></button>
		</td>
	</tr>
</script>
<script src="~/Scripts/jquery-3.3.1.min.js"></script>
<script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
<script src="~/Scripts/plugin/mustache.min.js"></script>
@RenderPage("popupView.cshtml")
<script>
	$(document).ready(function () {
		var sanpham = {
			init: function () {
				sanpham.loadsanpham();
				sanpham.events();
			},
			events: function () {
				$(document).on('click', '.btn-danger', function () {
					var MASP = $(this).data('id');
					sanpham.delete(MASP);
				})
				$(document).on('click', '.btn-edit', function () {
					$("#myModal").modal('show');


				});
			},
			delete: function (MASP) {
				$.ajax({
					url: '/Sanpham/deletesanpham',
					type: 'POST',
					data: { MASP: MASP },
					dataType: 'json',
					success: function (response) {
						if (response.status == true) {
							alert('xoa thanh cong');
							sanpham.loadsanpham();
						}

					}
				});
			},
			loadsanpham: function () {
				$.ajax({
					url: '/Sanpham/sanpham',
					type: 'GET',
					dataType: 'json',
					success: function (response) {
						if (response) {
							var data = response.data;
							var html = '';
							var template = $('#teamplatesanpham').html();
							$.each(data, function (i, item) {
								html += Mustache.render(template, {
									MASP: item.MASP,
									TENSP: item.TENSP,
									LOAISP: item.LOAISP,
									HANGSX: item.HANGSX,
									GIA: item.GIA,
									SOLUONG: item.SOLUONG,
									MOTA: item.MOTA,
									ANHDAIDIEN: item.ANHDAIDIEN

								});
							});
							$('#sp').html(html)
						}
					}
				});
			}
		}
		sanpham.init()
	})</script>

3012MVC/3012MVC/Areas/Admin/Views/Sanpham/popupView.cshtml
@section src{
	
}
<link href="~/admin-lte/css/StyleSheet1.css" rel="stylesheet" />
<div class="container">

	<!-- Trigger the modal with a button -->
	<!-- Modal -->
	<div class="modal fade" id="myModal" role="dialog" >
		<div class="modal-dialog" >

			<!-- Modal content-->
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal">&times;</button>
					<h4 class="modal-title">Add/Update Employee</h4>
				</div>
				<div class="modal-body">
					<form role="form" id="frmSaveData">
						<div class="form-group">
							<label for="txtName">Name:</label>
							<input type="text" class="form-control" name="txtName" id="txtName">
							<input type="hidden" id="hidID" value="0" />
						</div>
						<div class="form-group">
							<label for="txtemail">email:</label>
							<input type="text" class="form-control" name="txtemail" id="txtemail">
						</div>
						<div class="checkbox">
							<label><input type="checkbox" id="ckStatus">Active</label>
						</div>
						<div class="form-group">
							<label for="txtemail">email:</label>
							<input type="text" class="form-control" name="txtAddress" id="txtAddress">
						</div>
					</form>
				</div>
				<div class="modal-footer">
					<button type="submit" class="btn btn-primary" id="btnSave">Save</button>
					<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>

				</div>
			</div>

		</div>
	</div>

</div>

3012MVC/3012MVC/Areas/Admin/Views/Sanpham/themsp.cshtml
@model _3012MVC.Models.SPHAM

@{
    ViewBag.Title = "themsp";
}


@using (Html.BeginForm("Addsanpham","Sanpham",FormMethod.Post,new { enctype = "multipart/form-data" })) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
       <h5>Thêm sản phẩm</h5>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
       

        <div class="form-group">
           Tên sản phẩm
            <div class="col-md-10">
                @Html.EditorFor(model => model.TENSP, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TENSP, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
           Loại sản phẩm
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.LOAISP ,(SelectList)ViewBag.LOAISP, String.Empty,new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.LOAISP, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
         Hãng sản xuất
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.HANGSX ,(SelectList)ViewBag.HANGSX,String.Empty, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.HANGSX, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
          Giá gốc
            <div class="col-md-10">
                @Html.EditorFor(model => model.GIA, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GIA, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
          Số lượng
            <div class="col-md-10">
                @Html.EditorFor(model => model.SOLUONG, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SOLUONG, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
           Mô tả
            <div class="col-md-10">
                @Html.EditorFor(model => model.MOTA, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MOTA, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
          Sản phẩm mới
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.ISNEW)
                    @Html.ValidationMessageFor(model => model.ISNEW, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
          Ảnh đại diện
				<div class="col-md-3">
					<img id="anhnen" src="@Url.Content("~/template/")assets/images/blank.gif" alt="your image" />
					<input type="file" name="an" accept=".jpg" class="form-control" onchange="readURL(this, '#anhnen');" />
				</div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Tạo mới" class="btn btn-info btn-lg" />
            </div>
        </div>
    </div>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}